### ISSUE TITLE
Iniative system not working?

### ISSUE THREAD

**Issue by dinotheextinct** [free-beer/bh2e#10]
Hello,
I really enjoy your module, I used it to play a little adventure for my friends but it seems the initiative is not implemented? Regardlss of what icons one presses on the initiative tab no die rolls happen, nor does it seem possible to manually alter the initiative order?

**Comment by woodzer** [comment]
@dinotheextinct thanks for the report. I'll see if I can take a look at this sometime this evening.

**Comment by free-beer** [comment]
@dinotheextinct okay I've located some reference material to work from for this but it's going to take me a little time to get this functionality in there. I'll update here once I've got something to make available.

**Comment by dinotheextinct** [comment]
Thank you for your very fast reply and the work you put into it! Appreciate it, if I can be of any help let me know.

**Comment by free-beer** [comment]
Okay @dinotheextinct I've pushed version 0.3.0 that adds in what I hope if working Combat Tracker integration. If you get a chance can you pull the latest version and give it a go. I had to migrate some data as part of the change, so that might cause some issues. If you find anything then let me know. Otherwise I'll close this issue in a few days if I don't hear back from you.

**Comment by dinotheextinct** [comment]
Amazing! It seems to work, I just tested it briefly, also it autorolls after each round. Simply great man. Thank you very much for bringing this module to life and even fixing such a request so blazingly fast! Cheers. 

If I find any issues later on, Ill let you know. Thanks again.

**Comment by woodzer** [comment]
@dinotheextinct can I ask you to just check some of your creatures. The migration I made was to get hit points working consistently across characters and creatures and that meant changing the data model for creatures. If you can open a few of your creatures and check that their hit points values are showing correctly in the creature sheet that would be useful.

**Comment by free-beer** [comment]
I believe this issue has now been addressed so I'm closing it out.

**Comment by dinotheextinct** [comment]
Sorry for the late reply. I checked and it seems creatures still have the correct hit point value. But I didnt change much hp for creatures which I used so not sure thats proof everything is fine.
